# Generated by Django 4.1.3 on 2023-01-31 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_djangomigrations_delete_reviewvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamesGamescores',
        ),
    ]
