const anagrams = {
    5 : [
      [
        "abets",
        "baste",
        "betas",
        "beast",
        "beats"
      ],
      [
        "acres",
        "cares",
        "races",
        "scare"
      ],
      [
        "alert",
        "alter",
        "later"
      ],
      [
        "angel",
        "angle",
        "glean"
      ],
      [
        "baker",
        "brake",
        "break"
      ],
      [
        "bared",
        "beard",
        "bread",
        "debar"
      ],
      [
        "dater",
        "rated",
        "trade",
        "tread"
      ],
      [
        "below",
        "bowel",
        "elbow"
      ],
      [
        "caret",
        "cater",
        "crate",
        "trace",
        "react"
      ],
      [
        "weird",
        "wired",
        "wider"
      ],
      [
        "skate",
        "stake",
        "steak",
        "takes",
        "teaks"
      ],
      [
        "reins",
        "resin",
        "rinse",
        "risen",
        "siren"
      ],
      [
        "pores",
        "poser",
        "prose",
        "ropes",
        "spore"
      ],
      [
        "pines",
        "snipe",
        "spine"
      ],
      [
        "serve",
        "sever",
        "veers",
        "verse"
      ],
      [
        "rites",
        "tiers",
        "tires",
        "tries"
      ],
      [
        "pares",
        "parse",
        "pears",
        "reaps",
        "spare",
        "spear"
      ],
      [
        "noter",
        "toner",
        "tenor"
      ],
      [
        "least",
        "slate",
        "stale",
        "steal",
        "tales",
        "teals"
      ],
      [
        "mates",
        "meats",
        "steam",
        "tames",
        "teams"
      ]
    ],
    6 : [
      [
        "arrest",
        "rarest",
        "raster",
        "raters",
        "starer"
      ],
      [
        "carets",
        "caters",
        "caster",
        "crates",
        "reacts",
        "recast",
        "traces"
      ],
      [
        "canter",
        "nectar",
        "recant",
        "trance"
      ],
      [
        "danger",
        "gander",
        "garden",
        "ranged"
      ],
      [
        "daters",
        "trades",
        "treads",
        "stared"
      ],
      [
        "actors",
        "costar",
        "castor"
      ],
      [
        "actress",
        "casters",
        "recasts"
      ],
      [
        "bluest",
        "bluets",
        "bustle",
        "sublet",
        "subtle"
      ],
      [
        "bleats",
        "stable",
        "tables",
      ],
      [
        "drapes",
        "padres",
        "parsed",
        "rasped",
        "spared",
        "spread"
      ],
      [
        "enlist",
        "inlets",
        "listen",
        "silent",
        "tinsel"
      ],
      [
        "lister",
        "liters",
        "litres",
        "relist",
        "tilers"
      ],
      [
        "looped",
        "poodle",
        "pooled"
      ],
      [
        "palest",
        "pastel",
        "petals",
        "plates",
        "pleats",
        "staple"
      ],
      [
        "paltry",
        "partly",
        "raptly"
      ],
      [
        "master",
        "stream",
        "tamers"
      ]
    ],
    7 : [
      [
        "allergy",
        "gallery",
        "largely",
        "regally"
      ],
      [
        "aspired",
        "despair",
        "diapers",
        "praised"
      ],
      [
        "claimed",
        "decimal",
        "declaim",
        "medical"
      ],
      [
        "dearths",
        "hardest",
        "hatreds",
        "threads",
        "trashed"
      ],
      [
        "detains",
        "instead",
        "sainted",
        "stained"
      ],
      [
        "aridest",
        "astride",
        "staider",
        "tardies",
        "tirades"
      ],
      [
        "parsley",
        "parleys",
        "players",
        "replays",
        "sparely"
      ],
      [
        "esprits",
        "persist",
        "spriest",
        "sprites",
        "stripes"
      ],
      [
        "demerit",
        "merited",
        "mitered"
      ],
      [
        "enlarge",
        "general",
        "gleaner"
      ],
      [
        "observe",
        "obverse",
        "verbose"
      ],
      [
        "saltier",
        "realist",
        "retails"
      ]
    ],
    8 : [
      [
        "parroted",
        "predator",
        "prorated",
        "teardrop"
      ],
      [
        "repaints",
        "painters",
        "pantries",
        "pertains"
      ],
      [
        "restrain",
        "retrains",
        "strainer",
        "terrains",
        "trainers"
      ],
      [
        "construe",
        "counters",
        "recounts",
        "trounces"
      ],
      [
        "calipers",
        "replicas",
        "spiracle"
      ],
      [
        "lameness",
        "nameless",
        "salesman"
      ],
      [
        "decanter",
        "cantered",
        "recanted"
      ],
      [
        "thickets",
        "thickset",
        "thickest"
      ],
      [
        "designer",
        "redesign",
        "resigned"
      ],
      [
        "lameness",
        "nameless",
        "salesman"
      ]
    ]
  }

export default anagrams