# Generated by Django 4.1.3 on 2023-01-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('user', models.TextField()),
                ('game_id', models.IntegerField(choices=[(1, 'Math Game'), (2, 'Anagram Game')], default=1)),
                ('votes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(max_length=3000)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
