# Generated by Django 4.1.3 on 2023-01-18 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created'], 'verbose_name': 'Review'},
        ),
    ]
