# Generated by Django 4.1.3 on 2023-01-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_review_game_id_review_game_alter_review_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='username',
        ),
    ]
