# Generated by Django 4.1.3 on 2023-01-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.TextField(choices=[('MATH FACTS', 'Math Facts'), ('ANAGRAM HUNT', 'Anagram Hunt')], default='MATH FACTS'),
        ),
    ]
