# Generated by Django 4.1.3 on 2023-01-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_game_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Review ID'),
        ),
    ]
