# Generated by Django 4.1.3 on 2023-01-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescores',
            name='game',
            field=models.TextField(choices=[('MATH FACTS', 'Math Facts'), ('ANAGRAM HUNT', 'Anagram Hunt')], default='MATH FACTS'),
        ),
    ]
