# Generated by Django 4.1.3 on 2022-12-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescores',
            name='operation',
            field=models.TextField(default='x'),
            preserve_default=False,
        ),
    ]
