# Generated by Django 4.1.3 on 2022-12-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameScore',
            new_name='GameScores',
        ),
    ]
