# Generated by Django 4.1.3 on 2022-12-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamescores_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescores',
            name='gamelength',
            field=models.TextField(default='no record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamescores',
            name='maxnum',
            field=models.TextField(default='no record'),
            preserve_default=False,
        ),
    ]
